apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: demo-ui
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-ui
        tier: frontend
    spec:
      containers:
        - name: demo-ui
          image: bhargavrao19/demo-front
          ports:
            - name: ui
              containerPort: 5173