apiVersion: v1
kind: Service
metadata:
  name: demo-ui
spec:
  selector:
    app: demo-ui
    tier: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 5173
      targetPort: ui
      nodePort: 31300