apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 32000
  selector:
    app: mysqlpod
  type: NodePort
